### PR TITLE
feat: add support for delete-branch command

### PR DESCRIPTION
**Pull request by bethesque**
PACT-1466

### CODE REVIEW

**Comment by bethesque** [comment]
cc: @mefellows

**Comment by mefellows** [comment]
Nice - thanks!

**Review by YOU54F — APPROVED** [review]
Updated documentation and added a Branches -> delete-pact section above the `Tags` section

**Comment by bethesque** [comment]
Thanks @YOU54F. I'd forgotten that the new command had to be manually added to the script.

**Pull request merged**
